- name: Deploy Laravel
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      sudo mkdir -p /var/www/html
      sudo chown -R $USER:$USER /var/www/html
      cd /var/www/html

      if [ -d .git ]; then
        git reset --hard
        git clean -fd
        git pull origin main
      else
        sudo rm -rf /var/www/html/{*,.*} 2> /dev/null || true
        git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
        git checkout main
      fi

      mkdir -p storage bootstrap/cache

      chmod -R 775 storage
      chmod -R 775 bootstrap/cache

      if ! command -v docker-compose &> /dev/null; then
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      fi

      docker-compose down || true

      docker-compose up -d --build

      docker-compose exec server php artisan migrate --force
